name: stx_form_bloc
description: Easy Form State Management using BLoC pattern. Separate the Form State and Business Logic from the User Interface.
version: 1.0.9

homepage: https://github.com/VolodymyrSydorko/stx_form_bloc
repository: https://github.com/VolodymyrSydorko/stx_form_bloc
documentation: https://github.com/VolodymyrSydorko/stx_form_bloc

environment:
  sdk: '>=2.17.0 <3.0.0'


dependencies:
  bloc: ^8.1.0
  rxdart: ^0.27.5
  equatable: ^2.0.3
  uuid: ^3.0.6

dev_dependencies:
  lints: ^2.0.0
