name: stx_form_bloc
description: Easy Form State Management using BLoC pattern. Separate the Form State and Business Logic from the User Interface.
version: 1.0.0

homepage: https://github.com/VolodymyrSydorko/stx_form_bloc
repository: https://github.com/VolodymyrSydorko/stx_form_bloc
documentation: https://github.com/VolodymyrSydorko/stx_form_bloc

environment:
  sdk: '>=2.16.1 <3.0.0'


dependencies:
  bloc: ^8.0.3
  rxdart: ^0.27.3
  equatable: ^2.0.3
  uuid: ^3.0.6
  meta: ^1.7.0
  collection: ^1.16.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.2
