name: stx_form_bloc
description: Easy Form State Management using BLoC pattern. Separate the Form State and Business Logic from the User Interface.
version: 4.0.0

homepage: https://github.com/VolodymyrSydorko/stx_form_bloc
repository: https://github.com/VolodymyrSydorko/stx_form_bloc
documentation: https://github.com/VolodymyrSydorko/stx_form_bloc

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  bloc: ^9.0.0
  intl: ^0.20.2
  rxdart: ^0.28.0
  equatable: ^2.0.7
  uuid: ^4.5.1
  darq: ^2.0.0

dev_dependencies:
  test: ^1.25.14
  bloc_test: ^10.0.0
  mocktail: ^1.0.4
  lints: ^5.1.1
