name: stx_form_bloc
description: Easy Form State Management using BLoC pattern. Separate the Form State and Business Logic from the User Interface.
version: 2.0.2

homepage: https://github.com/VolodymyrSydorko/stx_form_bloc
repository: https://github.com/VolodymyrSydorko/stx_form_bloc
documentation: https://github.com/VolodymyrSydorko/stx_form_bloc

environment:
  sdk: '>=2.18.0 <3.0.0'


dependencies:
  bloc: ^8.1.0
  intl: ^0.17.0
  rxdart: ^0.27.5
  equatable: ^2.0.5
  uuid: ^3.0.6
  darq: ^1.2.1

dev_dependencies:
  test: ^1.21.6
  lints: ^2.0.0
