name: stx_form_bloc
description: Easy Form State Management using BLoC pattern. Separate the Form State and Business Logic from the User Interface.
version: 3.3.3

homepage: https://github.com/VolodymyrSydorko/stx_form_bloc
repository: https://github.com/VolodymyrSydorko/stx_form_bloc
documentation: https://github.com/VolodymyrSydorko/stx_form_bloc

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  bloc: ^8.1.4
  intl: ^0.19.0
  rxdart: ^0.27.7
  equatable: ^2.0.5
  uuid: ^4.4.0
  darq: ^2.0.0
  bloc_test: ^9.1.7
  
dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.5
  lints: ^4.0.0
