name: stx_form_bloc
description: Easy Form State Management using BLoC pattern. Separate the Form State and Business Logic from the User Interface.
version: 3.2.2

homepage: https://github.com/VolodymyrSydorko/stx_form_bloc
repository: https://github.com/VolodymyrSydorko/stx_form_bloc
documentation: https://github.com/VolodymyrSydorko/stx_form_bloc

environment:
  sdk: '>=2.18.0 <4.0.0'


dependencies:
  bloc: ^8.1.3
  intl: ^0.18.0
  rxdart: ^0.27.7
  equatable: ^2.0.5
  uuid: ^3.0.7
  darq: ^2.0.0
  bloc_test: ^9.1.6
  

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.2
  lints: ^3.0.0
