name: Run tests

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2.10.0

      - name: Install Dependencies
        run: flutter packages get

      - name: Run tests
        run: flutter test --no-pub --coverage --test-randomize-ordering-seed random
